### ISSUE TITLE
What sources were used to build crust.js?

### ISSUE THREAD

**Issue by craigleat** [bookiza/bookiza#9]
@marvindanig, what sources were used to build [crust.js](https://github.com/bookiza/bookiza/blob/master/crust/scripts/crust.js)?

I can see [Keymaster](https://github.com/madrobby/keymaster), [jQuery UI](https://jqueryui.com/), [iScroll](https://github.com/cubiq/iscroll) and [TurnJS](https://github.com/blasten/turn.js) in there plus other stuff I can't identify but seems to wrap around an online editor and there's all the reflow code...

Please acknowledge the sources and check in your build script, as one or more of these libraries may have licensing terms more restrictive than MIT.

**Comment by marvindanig** [comment]
Which library have you identified as more restrictive than MIT? 

Meanwhile, I'm looking into how acknowledgements were lost.

**Comment by craigleat** [comment]
This one caught my eye: TurnJS [license.](https://github.com/blasten/turn.js/blob/master/license.txt) There may be other third party sources in there I haven't identified - it's difficult to tell without the credits.

It would be much cleaner to include third party libs in their respective sub-folders under /src and have a build script create the bundle. With the current bundle how do you update a dependency?

Ps This [code](https://github.com/bookiza/bookiza/blob/02eb388447d9a466aade50dc892a929550ae62c4/crust/scripts/crust.js#L3204) surprises me ;-)

**Comment by marvindanig** [comment]
>  This one caught my eye: TurnJS license.

TurnJS is also available under [MIT](https://github.com/Youscribe/turn.js/commit/50b4c1101dd441d571baa32889b08d0c08e70a00). 

That said, we're aware about the [messy](https://github.com/blasten/turn.js/issues?utf8=%E2%9C%93&q=license+) [situation](https://github.com/blasten/turn.js/issues/61) regarding licensing options of Turnjs. The library has switched model to FOSS and back a few times in the past few years and its author doesn't seem to respond directly on the subject at the actual repo/website even though he seems to be active elsewhere or occasionally answers through other channels such as email. 

Due to lack of clarity and in good faith we have been working on our own new library, ground up, to match _or_ provide a subset of functionality from Turnjs. We hope to get it out in a few weeks. Stay hooked for that. 

>  There may be other third party sources in there I haven't identified ...

_and_

> I can see Keymaster, jQuery UI, iScroll and TurnJS in there plus other stuff I can't identify.

iScroll and jQuery_UI are not being used. Credits for keymaster and turn are back in place.
 
> It would be much cleaner to include third party libs in their respective sub-folders under /src and have a build script create the bundle.

Crust is planned to come in as a separate `npm module` per standard javascript techniques.

**Comment by craigleat** [comment]
> TurnJS is also available under MIT

This [commit](https://github.com/blasten/turn.js/commit/8db4c68a16aca1d82bd0eedd8ead5c187772e4b9#diff-b030a457ef94fcccb143cb4dd57ae14eL7) on the upstream repo is important and addresses my queries.

> Credits for keymaster and turn are back in place

That's great

> iScroll and jQuery_UI are not being used

The [momentum function](https://github.com/bookiza/bookiza/blob/1edaa7fb0ff46cbc1d0bdd68ffef9ed53836c8f0/crust/scripts/crust.js#L6224) [disappeared](https://github.com/bookiza/bookiza/commit/92ee303ec18d4feaaf1131891cd82061ba2619ac#diff-4accfa45bd3a175ca4cce3b81bcc3ec6) over the weekend. No problem with the [book slider](https://github.com/bookiza/bookiza/blob/f6e8f0f495d35c124f4cd5626a74b348c29d909a/crust/scripts/crust.js#L4147) it seems to only be a distant cousin of the jQuery UI slider.
